# Generated by Django 5.2 on 2025-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_alter_board_member_count_alter_board_owner_id'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
