# Generated by Django 5.2 on 2025-05-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ticket_count', models.IntegerField(default=0)),
                ('tasks_to_do_count', models.IntegerField(default=0)),
                ('task_hight_prio_count', models.IntegerField(default=0)),
                ('member_count', models.ManyToManyField(related_name='board', to='user_auth_app.userprofile')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to='user_auth_app.userprofile')),
            ],
        ),
    ]
