# Generated by Django 5.2 on 2025-05-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='task_hight_prio_count',
            new_name='tasks_high_prio_count',
        ),
    ]
