# Generated by Django 5.2 on 2025-05-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_remove_board_member_count_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
